export const VGEN_CREATE_VIDEO_GENERATOR_MODEL_NAME = process.env.VGEN_CREATE_VIDEO_GENERATOR_MODEL_NAME || 'llama3.1';
export const VGEN_AUDIO_GENERATOR_MODEL_NAME = process.env.VGEN_AUDIO_GENERATOR_MODEL_NAME || 'ar-diff-50k';
export const VGEN_VIDEO_GENERATOR_MODEL_NAME = process.env.VGEN_VIDEO_GENERATOR_MODEL_NAME || 'llama3.1';
export const VGEN_CLEAN_SRT_GENERATOR_MODEL_NAME = process.env.VGEN_CLEAN_SRT_GENERATOR_MODEL_NAME || 'llama3.1';
export const VGEN_TRANSCRIPT_GENERATOR_MODEL_NAME = process.env.VGEN_TRANSCRIPT_GENERATOR_MODEL_NAME || 'llama3.1';
export const VGEN_VIDEO_TITLE_GENERATOR_MODEL_NAME = process.env.VGEN_VIDEO_TITLE_GENERATOR_MODEL_NAME || 'llama3.1';
export const VGEN_IMAGE_GENERATOR_MODEL_NAME = process.env.VGEN_IMAGE_GENERATOR_MODEL_NAME || 'dalle3'
